name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
	working-directory: movie-analyst-api
        run: npm ci

      - name: Run tests
	working-directory: movie-analyst-api
        run: npm test || echo "No tests configured"

      - name: Build project
	working-directory: movie-analyst-api
        run: npm run build || echo "No tests configured"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: api-build-artifacts
          path: movie-analyst-api/dist/
